// Code generated by protoc-gen-go. DO NOT EDIT.
// source: OnlineState.proto

package OnlineState

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OnlineInfo struct {
	// true; 查询的账号
	Account string `protobuf:"bytes,6,opt,name=account,proto3" json:"account"`
	// true; 状态; 1, ONLINE; 2, OFFLINE;
	Online int32 `protobuf:"varint,7,opt,name=online,proto3" json:"online"`
	// true; 最后在线时间,ms
	LastTime int64 `protobuf:"varint,8,opt,name=last_time,json=lastTime,proto3" json:"last_time"`
	// true; 连接信息
	ConnInfo string `protobuf:"bytes,9,opt,name=conn_info,json=connInfo,proto3" json:"conn_info"`
	// true; 0 normal, 1 sleep
	Sleep int32 `protobuf:"varint,10,opt,name=sleep,proto3" json:"sleep"`
	// true; 连接的PPMQD服务器地址
	SrvId                string   `protobuf:"bytes,11,opt,name=srv_id,json=srvId,proto3" json:"srv_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineInfo) Reset()         { *m = OnlineInfo{} }
func (m *OnlineInfo) String() string { return proto.CompactTextString(m) }
func (*OnlineInfo) ProtoMessage()    {}
func (*OnlineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_afccbb90f88db7d1, []int{0}
}

func (m *OnlineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineInfo.Unmarshal(m, b)
}
func (m *OnlineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineInfo.Marshal(b, m, deterministic)
}
func (m *OnlineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineInfo.Merge(m, src)
}
func (m *OnlineInfo) XXX_Size() int {
	return xxx_messageInfo_OnlineInfo.Size(m)
}
func (m *OnlineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineInfo proto.InternalMessageInfo

func (m *OnlineInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OnlineInfo) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *OnlineInfo) GetLastTime() int64 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

func (m *OnlineInfo) GetConnInfo() string {
	if m != nil {
		return m.ConnInfo
	}
	return ""
}

func (m *OnlineInfo) GetSleep() int32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

func (m *OnlineInfo) GetSrvId() string {
	if m != nil {
		return m.SrvId
	}
	return ""
}

// Reqest
type Req struct {
	// true; 需要查询的账号; 如果是设备则是设备ID,如果是用户则是userid
	Accounts             []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_afccbb90f88db7d1, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Response
type Resp struct {
	// true; 在线情况汇总
	Stas                 []*OnlineInfo `protobuf:"bytes,1,rep,name=stas,proto3" json:"stas"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_afccbb90f88db7d1, []int{2}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetStas() []*OnlineInfo {
	if m != nil {
		return m.Stas
	}
	return nil
}

func init() {
	proto.RegisterType((*OnlineInfo)(nil), "OnlineState.OnlineInfo")
	proto.RegisterType((*Req)(nil), "OnlineState.Req")
	proto.RegisterType((*Resp)(nil), "OnlineState.Resp")
}

func init() { proto.RegisterFile("OnlineState.proto", fileDescriptor_afccbb90f88db7d1) }

var fileDescriptor_afccbb90f88db7d1 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x6e, 0xc3, 0x20,
	0x14, 0x85, 0x8b, 0x1c, 0x1c, 0xfb, 0x7a, 0x69, 0xae, 0xfa, 0x83, 0xd2, 0xc5, 0xf5, 0x64, 0xa9,
	0x92, 0x87, 0x64, 0xe8, 0x03, 0x74, 0xca, 0x54, 0x8b, 0x76, 0xb7, 0xa8, 0x43, 0x24, 0x24, 0x02,
	0xc4, 0xd0, 0xbc, 0x51, 0xdf, 0xb3, 0x32, 0x4e, 0xd4, 0x34, 0xe3, 0xf7, 0xdd, 0xc3, 0x01, 0x2e,
	0x2c, 0xde, 0x8d, 0x56, 0x46, 0x7e, 0x04, 0x11, 0x64, 0xe3, 0x06, 0x1b, 0x2c, 0x16, 0x17, 0xaa,
	0xfa, 0x21, 0x00, 0x13, 0x6f, 0xcc, 0xce, 0x22, 0x83, 0xb9, 0xe8, 0x7b, 0xfb, 0x6d, 0x02, 0x4b,
	0x4b, 0x52, 0xe7, 0xfc, 0x8c, 0xf8, 0x00, 0xa9, 0x8d, 0x39, 0x36, 0x2f, 0x49, 0x4d, 0xf9, 0x89,
	0xf0, 0x09, 0x72, 0x2d, 0x7c, 0xe8, 0x82, 0xda, 0x4b, 0x96, 0x95, 0xa4, 0x4e, 0x78, 0x36, 0x8a,
	0x4f, 0xb5, 0x8f, 0xc3, 0xde, 0x1a, 0xd3, 0x29, 0xb3, 0xb3, 0x2c, 0x8f, 0x85, 0xd9, 0x28, 0xe2,
	0x5d, 0x77, 0x40, 0xbd, 0x96, 0xd2, 0x31, 0x88, 0x85, 0x13, 0xe0, 0x3d, 0xa4, 0x7e, 0x38, 0x76,
	0x6a, 0xcb, 0x8a, 0x98, 0xa7, 0x7e, 0x38, 0x6e, 0xb6, 0xd5, 0x33, 0x24, 0x5c, 0x1e, 0x70, 0x09,
	0xd9, 0xe9, 0x41, 0x9e, 0x91, 0x32, 0x19, 0xfb, 0xce, 0x5c, 0xad, 0x61, 0xc6, 0xa5, 0x77, 0xf8,
	0x02, 0x33, 0x1f, 0xc4, 0x34, 0x2f, 0x56, 0x8f, 0xcd, 0xe5, 0x06, 0xfe, 0xbe, 0xca, 0x63, 0x68,
	0xf5, 0x0a, 0xb4, 0x6d, 0xb9, 0xeb, 0xb1, 0x01, 0xda, 0xbe, 0x09, 0xad, 0xf1, 0xf6, 0xdf, 0x01,
	0x2e, 0x0f, 0xcb, 0xc5, 0x95, 0xf1, 0xae, 0xba, 0xf9, 0x4a, 0xe3, 0x32, 0xd7, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0x86, 0x23, 0xf0, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PPRpcClient is the client API for PPRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPRpcClient interface {
	PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type pPRpcClient struct {
	cc *grpc.ClientConn
}

func NewPPRpcClient(cc *grpc.ClientConn) PPRpcClient {
	return &pPRpcClient{cc}
}

func (c *pPRpcClient) PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/OnlineState.PPRpc/PCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPRpcServer is the server API for PPRpc service.
type PPRpcServer interface {
	PCall(context.Context, *Req) (*Resp, error)
}

func RegisterPPRpcServer(s *grpc.Server, srv PPRpcServer) {
	s.RegisterService(&_PPRpc_serviceDesc, srv)
}

func _PPRpc_PCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPRpcServer).PCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OnlineState.PPRpc/PCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPRpcServer).PCall(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OnlineState.PPRpc",
	HandlerType: (*PPRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PCall",
			Handler:    _PPRpc_PCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "OnlineState.proto",
}
