// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PPMQGetClientID.proto

package PPMQGetClientID

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reqest
type Req struct {
	// true; 验证使用的账户;Device时为 did; user时为 user_id 转变为字符串
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account"`
	// true; 硬件特征 hardware_info(同一台设备的特征码要保持一致)
	HardwareInfo         string   `protobuf:"bytes,3,opt,name=hardware_info,json=hardwareInfo,proto3" json:"hardware_info"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda708cbb08ea77d, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Req) GetHardwareInfo() string {
	if m != nil {
		return m.HardwareInfo
	}
	return ""
}

// Response
type Resp struct {
	// true; 设备唯一ID号(同一个帐号在相同的设备上得到的ClientId是一致的)
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda708cbb08ea77d, []int{1}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*Req)(nil), "PPMQGetClientID.Req")
	proto.RegisterType((*Resp)(nil), "PPMQGetClientID.Resp")
}

func init() { proto.RegisterFile("PPMQGetClientID.proto", fileDescriptor_dda708cbb08ea77d) }

var fileDescriptor_dda708cbb08ea77d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0d, 0x08, 0xf0, 0x0d,
	0x74, 0x4f, 0x2d, 0x71, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xf1, 0x74, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x72, 0xe1, 0x62, 0x0e, 0x4a, 0x2d, 0x14, 0x92, 0xe0, 0x62,
	0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x85, 0x94, 0xb9, 0x78, 0x33, 0x12, 0x8b, 0x52, 0xca, 0x13, 0x8b, 0x52, 0xe3, 0x33, 0xf3, 0xd2,
	0xf2, 0x25, 0x98, 0xc1, 0xf2, 0x3c, 0x30, 0x41, 0xcf, 0xbc, 0xb4, 0x7c, 0x25, 0x65, 0x2e, 0x96,
	0xa0, 0xd4, 0xe2, 0x02, 0x21, 0x69, 0x2e, 0xce, 0x64, 0xb0, 0xc9, 0xf1, 0x99, 0x29, 0x12, 0x8c,
	0x60, 0x85, 0x1c, 0x10, 0x01, 0xcf, 0x14, 0x23, 0x7b, 0x2e, 0xd6, 0x80, 0x80, 0xa0, 0x82, 0x64,
	0x21, 0x33, 0x2e, 0xd6, 0x00, 0xe7, 0xc4, 0x9c, 0x1c, 0x21, 0x11, 0x3d, 0x74, 0x57, 0x06, 0xa5,
	0x16, 0x4a, 0x89, 0x62, 0x11, 0x2d, 0x2e, 0x50, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xc1, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0xb8, 0xad, 0x4f, 0xdc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PPRpcClient is the client API for PPRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPRpcClient interface {
	PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type pPRpcClient struct {
	cc *grpc.ClientConn
}

func NewPPRpcClient(cc *grpc.ClientConn) PPRpcClient {
	return &pPRpcClient{cc}
}

func (c *pPRpcClient) PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/PPMQGetClientID.PPRpc/PCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPRpcServer is the server API for PPRpc service.
type PPRpcServer interface {
	PCall(context.Context, *Req) (*Resp, error)
}

func RegisterPPRpcServer(s *grpc.Server, srv PPRpcServer) {
	s.RegisterService(&_PPRpc_serviceDesc, srv)
}

func _PPRpc_PCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPRpcServer).PCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPMQGetClientID.PPRpc/PCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPRpcServer).PCall(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PPMQGetClientID.PPRpc",
	HandlerType: (*PPRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PCall",
			Handler:    _PPRpc_PCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PPMQGetClientID.proto",
}
