// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PPMQOAONotify.proto

package PPMQOAONotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reqest
type Req struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	// 1: offline; 2: online
	Status  int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	UserId  int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Account string `protobuf:"bytes,4,opt,name=account,proto3" json:"account"`
	// 1 sleep hb; 0 no sleep hb
	IsSleep int32 `protobuf:"varint,5,opt,name=is_sleep,json=isSleep,proto3" json:"is_sleep"`
	// On/Off line 通过 server_id判断是否需要更新设备的在离线状态.
	ServerId string `protobuf:"bytes,6,opt,name=server_id,json=serverId,proto3" json:"server_id"`
	// true
	Ipaddr               string   `protobuf:"bytes,7,opt,name=ipaddr,proto3" json:"ipaddr"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_8674637ceb02778f, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Req) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Req) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Req) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Req) GetIsSleep() int32 {
	if m != nil {
		return m.IsSleep
	}
	return 0
}

func (m *Req) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *Req) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

// Response
type Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8674637ceb02778f, []int{1}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Req)(nil), "PPMQOAONotify.Req")
	proto.RegisterType((*Resp)(nil), "PPMQOAONotify.Resp")
}

func init() { proto.RegisterFile("PPMQOAONotify.proto", fileDescriptor_8674637ceb02778f) }

var fileDescriptor_8674637ceb02778f = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0x69, 0x9c, 0xf6, 0x24, 0x96, 0xab, 0x04, 0x06, 0x96, 0x28, 0x53, 0xa6, 0x0e,
	0x65, 0x64, 0x42, 0x4c, 0x1d, 0xa0, 0xc6, 0x3c, 0x40, 0x15, 0xe2, 0x43, 0xb2, 0x14, 0x35, 0x6e,
	0xce, 0x41, 0xe2, 0xe1, 0x78, 0x37, 0x14, 0xbb, 0x0c, 0x11, 0xe3, 0xf7, 0x9d, 0xee, 0xd7, 0x7f,
	0x07, 0x6b, 0xad, 0x5f, 0xde, 0xf6, 0x4f, 0xfb, 0xd7, 0x3e, 0xb8, 0xcf, 0xef, 0x8d, 0x1f, 0xfa,
	0xd0, 0xe3, 0xd5, 0x4c, 0x56, 0x3f, 0x02, 0x32, 0x43, 0x27, 0xbc, 0x87, 0x55, 0xdb, 0x39, 0x3a,
	0x86, 0x83, 0xb3, 0x4a, 0x94, 0xa2, 0x5e, 0x99, 0x65, 0x12, 0x3b, 0x8b, 0xd7, 0x20, 0x39, 0x34,
	0x61, 0x64, 0x75, 0x59, 0x8a, 0x3a, 0x37, 0x67, 0xc2, 0x1b, 0x28, 0x46, 0xa6, 0x61, 0x5a, 0xc9,
	0x4a, 0x51, 0x67, 0x46, 0x4e, 0xb8, 0xb3, 0xa8, 0xa0, 0x68, 0xda, 0xb6, 0x1f, 0x8f, 0x41, 0x2d,
	0x62, 0xd6, 0x1f, 0xe2, 0x2d, 0x2c, 0x1d, 0x1f, 0xb8, 0x23, 0xf2, 0x2a, 0x8f, 0x61, 0x85, 0xe3,
	0xf7, 0x09, 0xa7, 0x0a, 0x4c, 0xc3, 0x57, 0xca, 0x93, 0xa9, 0x42, 0x12, 0xa9, 0x82, 0xf3, 0x8d,
	0xb5, 0x83, 0x2a, 0xe2, 0xe4, 0x4c, 0x95, 0x84, 0x85, 0x21, 0xf6, 0xdb, 0x47, 0xc8, 0xb5, 0x36,
	0xbe, 0xc5, 0x2d, 0xe4, 0xfa, 0xb9, 0xe9, 0x3a, 0xc4, 0xcd, 0xfc, 0x7c, 0x43, 0xa7, 0xbb, 0xf5,
	0x3f, 0xc7, 0xbe, 0xba, 0xf8, 0x90, 0xf1, 0x35, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0xa6, 0x5d, 0xfc, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PPRpcClient is the client API for PPRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPRpcClient interface {
	PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type pPRpcClient struct {
	cc *grpc.ClientConn
}

func NewPPRpcClient(cc *grpc.ClientConn) PPRpcClient {
	return &pPRpcClient{cc}
}

func (c *pPRpcClient) PCall(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/PPMQOAONotify.PPRpc/PCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPRpcServer is the server API for PPRpc service.
type PPRpcServer interface {
	PCall(context.Context, *Req) (*Resp, error)
}

func RegisterPPRpcServer(s *grpc.Server, srv PPRpcServer) {
	s.RegisterService(&_PPRpc_serviceDesc, srv)
}

func _PPRpc_PCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPRpcServer).PCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPMQOAONotify.PPRpc/PCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPRpcServer).PCall(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PPMQOAONotify.PPRpc",
	HandlerType: (*PPRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PCall",
			Handler:    _PPRpc_PCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PPMQOAONotify.proto",
}
